// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"FileStore-System/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddVolumeReq       = user.AddVolumeReq
	AddVolumeResp      = user.AddVolumeResp
	DecreaseVolumeReq  = user.DecreaseVolumeReq
	DecreaseVolumeResp = user.DecreaseVolumeResp
	VolumeDetailReq    = user.VolumeDetailReq
	VolumeDetailResp   = user.VolumeDetailResp

	User interface {
		DecreaseVolume(ctx context.Context, in *DecreaseVolumeReq, opts ...grpc.CallOption) (*DecreaseVolumeResp, error)
		GetVolumeByUserId(ctx context.Context, in *VolumeDetailReq, opts ...grpc.CallOption) (*VolumeDetailResp, error)
		AddVolume(ctx context.Context, in *AddVolumeReq, opts ...grpc.CallOption) (*AddVolumeResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) DecreaseVolume(ctx context.Context, in *DecreaseVolumeReq, opts ...grpc.CallOption) (*DecreaseVolumeResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DecreaseVolume(ctx, in, opts...)
}

func (m *defaultUser) GetVolumeByUserId(ctx context.Context, in *VolumeDetailReq, opts ...grpc.CallOption) (*VolumeDetailResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetVolumeByUserId(ctx, in, opts...)
}

func (m *defaultUser) AddVolume(ctx context.Context, in *AddVolumeReq, opts ...grpc.CallOption) (*AddVolumeResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddVolume(ctx, in, opts...)
}
