// Code generated by goctl. DO NOT EDIT.
package types

type ShareDetailRequest struct {
	ShareURL string `json:"share_url"`
}

type ShareDetailResponse struct {
	ShareDetails []*ShareDetail `json:"share_details"`
}

type ShareDetail struct {
	StoreId   string `json:"store_id"`
	Name      string `json:"name"`
	Size      int64  `json:"size"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CreateShareRequest struct {
	StoreIds    []string `json:"store_ids"`
	ExpiredTime int64    `json:"expire_time"`
}

type CreateShareResponse struct {
	ShareURL string `json:"share_url"`
}

type SaveFromShareRequest struct {
	StoreIds   []string `json:"store_ids"`
	ShareURL   string   `json:"share_url"`
	ToParentId string   `json:"to_parent_id"` //保存在该parentId目录下
}

type SaveFromShareResponse struct {
}
