// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStoreFieldNames          = builder.RawFieldNames(&UserStore{})
	userStoreRows                = strings.Join(userStoreFieldNames, ",")
	userStoreRowsExpectAutoSet   = strings.Join(stringx.Remove(userStoreFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	userStoreRowsWithPlaceHolder = strings.Join(stringx.Remove(userStoreFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cacheUserStoreIdPrefix       = "cache:userStore:id:"
	cacheUserStoreParentIdPrefix = "cache:userStore:parentId:"
)

type (
	userStoreModel interface {
		Insert(ctx context.Context, data *UserStore) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserStore, error)
		Update(ctx context.Context, data *UserStore) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserStoreModel struct {
		sqlc.CachedConn
		table string
	}

	UserStore struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		ParentId   int64     `db:"parent_id"`
		StoreId    int64     `db:"store_id"` // 0则为文件夹
		Name       string    `db:"name"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newUserStoreModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserStoreModel {
	return &defaultUserStoreModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_store`",
	}
}

func (m *defaultUserStoreModel) Delete(ctx context.Context, id int64) error {
	userStoreIdKey := fmt.Sprintf("%s%v", cacheUserStoreIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userStoreIdKey)
	return err
}

func (m *defaultUserStoreModel) FindOne(ctx context.Context, id int64) (*UserStore, error) {
	userStoreIdKey := fmt.Sprintf("%s%v", cacheUserStoreIdPrefix, id)
	var resp UserStore
	err := m.QueryRowCtx(ctx, &resp, userStoreIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStoreRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStoreModel) Insert(ctx context.Context, data *UserStore) (sql.Result, error) {
	userStoreIdKey := fmt.Sprintf("%s%v", cacheUserStoreIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userStoreRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ParentId, data.StoreId, data.Name)
	}, userStoreIdKey)
	return ret, err
}

func (m *defaultUserStoreModel) Update(ctx context.Context, data *UserStore) error {
	userStoreIdKey := fmt.Sprintf("%s%v", cacheUserStoreIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userStoreRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ParentId, data.StoreId, data.Name, data.Id)
	}, userStoreIdKey)
	return err
}

func (m *defaultUserStoreModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserStoreIdPrefix, primary)
}

func (m *defaultUserStoreModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userStoreRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserStoreModel) tableName() string {
	return m.table
}
