// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FileStore-System/service/store/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/list",
				Handler: FileListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/folder/list",
				Handler: FolderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/name/update",
				Handler: FileNameUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/folder/create",
				Handler: FolderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/folder/delete",
				Handler: FolderDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/delete",
				Handler: FileDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/move",
				Handler: FileMoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/chunk/upload",
				Handler: FileUploadByChunkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/download",
				Handler: FileDownloadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
